######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 4 10:55:13 2012
######################################################################

TEMPLATE = app
TARGET = roomRez
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qstd.h utils_export.h \
    roomRez.h
SOURCES += main.cpp qstd.cpp \
    roomRez.cpp
