######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 4 11:46:16 2013
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += profFunc.h
SOURCES += profFunc.cpp testproffunc.cpp
